name: Build
on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  encapsulate:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        variant: [silverblue]
        version: [39]
    runs-on: ubuntu-latest
    container:
      # We're using coreos-assembler just since it is a pre-made
      # container with rpm-ostree
      image: quay.io/coreos-assembler/coreos-assembler:latest
      options: "--user root --privileged -v /srv:/srv"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login
        run: podman login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
      - name: Encapsulate Testing
        if: ${{ matrix.version  == '37' }}
        run: ./encap.sh fedora/${{ matrix.version }}/x86_64/testing/${{ matrix.variant }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/fedora-${{ matrix.variant }}:${{ matrix.version }}
      #- name: Encapsulate Rawhide
      #  if: ${{ matrix.version == 'rawhide' }} 
      #  run: ./encap.sh fedora/${{ matrix.version }}/x86_64/${{ matrix.variant }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/fedora-${{ matrix.variant }}:${{ matrix.version }}
      - name: Encapsulate F39
        if: ${{ matrix.version == '39' }} 
        run: ./encap.sh fedora/${{ matrix.version }}/x86_64/${{ matrix.variant }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/fedora-${{ matrix.variant }}:${{ matrix.version }}
